Wrong  declaration of case "miopenActivationPATHTRU" . It should be "miopenActivationPASTHRU"
As per https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/include/miopen/miopen.h Line : 350.,
enum is defined as "miopenActivationPASTHRU" but in hipDNN , it is miopenActivationPATHTRU.
Due to this issue, hipDNN building is failing.

src/hcc_detail/hipDNN_miopen.cpp:374:10: error: use of undeclared identifier 'miopenActivationPATHTRU'; did you mean
      'miopenActivationPASTHRU'?
    case miopenActivationPATHTRU:
         ^~~~~~~~~~~~~~~~~~~~~~~
         miopenActivationPASTHRU
/opt/rocm/miopen/include/miopen/miopen.h:352:5: note: 'miopenActivationPASTHRU' declared here
    miopenActivationPASTHRU  = 0, /*!< No activation, pass through the data */
    ^
1 error generated.